### PR TITLE
Update l298n.py

### PR DESCRIPTION
**Pull request by espresso0000**
Change to allow for modification of L/R different from F/B

### CODE REVIEW

**Comment by Nocturnal42** [comment]
I'm going to have to ask for a more detailed description of why these changes are needed / a good thing.

Also, you commit includes code that should not be added to the main repo.

**Comment by espresso0000** [comment]
The reason for the changes was for improved control of my tank drive chassis.  As original the L & R i felt turned to far per single movement control, the change allowed for more precision in the turning abilities while independent from the speed & distance traveled per instance/single movement of a F & B drive.  Those were also modified to travel less distance per command while maintaining a good rate of speed.
The changes were originally made while in a controlled environment and have worked well for my chassis, while still being able to be set to original settings for others that may not observe the benefit.

**Comment by Nocturnal42** [comment]
Except you could have achieved exactly the same effect, without changing the code, just by changing the values of sleeptime & rotatetimes. All you've done is replaced one set of variables with another.

sleeptime determines how long the motors run when going forward / backwards. rotatetimes is a multiplier on that, that can either increase or decrease it for turning.

**Comment by espresso0000** [comment]
The change was to allow a different variable for L/R then used for F/B

**Comment by espresso0000** [comment]
Allowing for a letsrobot.conf settings of:
sleeptime=0.2
turn_sleeptime=0.1
rotatetimes=2

**Comment by Nocturnal42** [comment]
Since turn_sleeptime only purpose was as a modifier to sleeptime, to allow changing the turning times. It is redundant in your code (ie not needed).

You also could have achieved the same effect with two single line changes. i.e. changing this...
`time.sleep(sleeptime * rotatetimes)`
to this...
`time.sleep(rotatetimes)`

I didn't add support for l298n, so I don't know why they original author linked forward travel with turning travel. I assume that the idea was if you have to modify forward / backward times to account for different surfaces, its useful to not also have to change turning as well. 

Since both values can be easily changed on the fly, and I know the current method confuses people, I am inclined to unlink them, though I will have to ask around a little first.

**Comment by reltham** [comment]
To achieve:
sleeptime=0.2
turn_sleeptime=0.1
You would do this with the old values:
sleeptime=0.2
rotatetimes=0.5

**Comment by espresso0000** [comment]
going back to original code and sleeptime=0.2 rotatetimes=0.5  my turn is corrected to desired amount but now distance traveled F/B is also reduced by half. (utilizing no changes to l298n.py)

**Comment by reltham** [comment]
So make sleeptime a bigger number and rotatetimes a smaller fraction appropriately

**Comment by espresso0000** [comment]
Ah yes that did the trick, then my apologies,
sleeptime=0.4
rotatetimes=0.25
did the trick.  That was always a confusing way i thought it was done, and do notice there was a change since old repo had the multiplier on the F/B which is now on the L/R  so I had to rethink my variables.  Appreciate entertaining my problem, and thank you for helping me better understand that configuration now.

**Pull request closed without merging**
